### ISSUE TITLE
executable force closing , after the "Checking for requirements" screen

### ISSUE THREAD

**Issue by theoctavist** [hellzerg/optimizer#167]
[https://imgur.com/gallery/gRa4mUw](url)

https://imgur.com/gallery/gRa4mUw

file not blocked, no antivirus active, windows defender disabled, running as admin, nothing works.

**Comment by hellzerg** [comment]
Send me the Optimizer.log in C:\ProgramData\Optimizer

**Comment by theoctavist** [comment]
Will do! Thank you so much

**Comment by theoctavist** [comment]
`Windows 10 Pro - 2009 (64-bit)
Optimizer 11.7 - .NET Framework 4.8 - Experimental build: False


[ERROR] [2/11/2022 3:43:18 AM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-


[ERROR] [2/11/2022 3:43:18 AM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.Optimize.DisableVisualStudioTelemetry()


[ERROR] [2/11/2022 3:43:53 AM] in function [Utilities.OpenSubKeyWritable]
Subkey DPS not found.

-


[ERROR] [2/11/2022 8:26:59 PM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-


[ERROR] [2/11/2022 8:26:59 PM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.Optimize.DisableVisualStudioTelemetry()


[ERROR] [2/12/2022 9:31:44 PM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-


[ERROR] [2/12/2022 9:31:44 PM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.Optimize.DisableVisualStudioTelemetry()


[ERROR] [2/16/2022 2:17:12 AM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-


[ERROR] [2/16/2022 2:17:12 AM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.Optimize.DisableVisualStudioTelemetry()


[ERROR] [4/22/2022 11:09:25 PM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-


[ERROR] [4/22/2022 11:09:25 PM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.Optimize.DisableVisualStudioTelemetry()


[ERROR] [4/22/2022 11:09:27 PM] in function [Utilities.OpenSubKeyWritable]
Subkey DPS not found.

-


[ERROR] [4/22/2022 11:10:09 PM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-


[ERROR] [4/22/2022 11:10:09 PM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.Optimize.DisableVisualStudioTelemetry()


[ERROR] [4/22/2022 11:10:09 PM] in function [Utilities.OpenSubKeyWritable]
Subkey DPS not found.

-


[ERROR] [4/22/2022 11:36:51 PM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-


[ERROR] [4/22/2022 11:36:51 PM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.Optimize.DisableVisualStudioTelemetry()


[ERROR] [4/22/2022 11:36:52 PM] in function [Utilities.OpenSubKeyWritable]
Subkey DPS not found.

-


[ERROR] [4/22/2022 11:39:58 PM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-


[ERROR] [4/22/2022 11:39:58 PM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.Optimize.DisableVisualStudioTelemetry()


[ERROR] [4/22/2022 11:39:58 PM] in function [Utilities.OpenSubKeyWritable]
Subkey DPS not found.

-


`

**Comment by theoctavist** [comment]
[Optimizer.log](https://github.com/hellzerg/optimizer/files/8549283/Optimizer.log)

**Comment by hellzerg** [comment]
Did you try deleting the Optimizer folder in ProgramData, amd re-running the app?

**Comment by theoctavist** [comment]
> Did you try deleting the Optimizer folder in ProgramData, amd re-running the app?

Nossir, will do though and report back. Thank you !

**Comment by HBenzaoui** [comment]
> Did you try deleting the Optimizer folder in ProgramData, amd re-running the app?

I have the same problem i did delete the folder and rerun it and still same problem

**Comment by theoctavist** [comment]
> Did you try deleting the Optimizer folder in ProgramData, amd re-running the app?

yessir, worked great! thank you.

**Comment by Shambdebjit** [comment]
sir can you help me how do I fix the same problem? I don't know how to solve this by the steps you provide upper section. please sir can you please provide step by step tutorial on this?

**Comment by hellzerg** [comment]
> sir can you help me how do I fix the same problem? I don't know how to solve this by the steps you provide upper section. please sir can you please provide step by step tutorial on this?

Did you delete the aforementioned folder?

**Comment by Shambdebjit** [comment]
yes sir I delete the folder you provide in upper section. But still it dose not work. sir please tell me what can I do  .

**Comment by hellzerg** [comment]
> yes sir I delete the folder you provide in upper section. But still it dose not work. sir please tell me what can I do .

Please, tell me exactly what's the problem?
