### ISSUE TITLE
Problem opening Optimizer.exe

### ISSUE THREAD

**Issue by HLBox** [hellzerg/optimizer#200]
Hello.  When I open the latest version of Optimizer, I get the loading interface but after it finishes loading, it crashes and closes.  I already checked if my antivirus was stopping it for me but no, I also checked if it was meeting the requirements and it was meeting them.  I think it's a program error.  I use Windows 10 21H2, Net Framework 4.8.

**Comment by hellzerg** [comment]
Can you send me the optimizer.log file in C:\ProgramData\Optimizer?

**Comment by HLBox** [comment]
@hellzerg 

Windows 10 Pro - 2009 (64-bit)
Optimizer 13.6 - .NET Framework 4.8 - Experimental build: False


[ERROR] [7/12/2022 4:09:23 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()


[ERROR] [7/12/2022 4:09:23 PM] in function [MainForm.GetFeed-DownloadImages]
The remote name could not be resolved: 'raw.githubusercontent.com'

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at Optimizer.MainForm.GetFeed()


[ERROR] [7/12/2022 8:57:37 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()


[ERROR] [7/12/2022 8:57:38 PM] in function [MainForm.GetFeed-DownloadImages]
The remote name could not be resolved: 'raw.githubusercontent.com'

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at Optimizer.MainForm.GetFeed()

**Comment by hellzerg** [comment]
I need the DUMP file too..

**Comment by HLBox** [comment]
@hellzerg How do I send you the DUMP file?

**Comment by hellzerg** [comment]
@HLBox zip it and upload it here

**Comment by HLBox** [comment]
@hellzerg 

[Uploading Optimizer-13.6.exe.7660.zip…]()

**Comment by PhoenixCODE2322** [comment]
@hellzerg i am facing the same, i was trying to disable defender, so what i did reboot  to safe mode manually (i read the instruction wrong) , then tried opening optimizer but loading shows and then it disappears. then i opened cmd and passed this /disabledefender but it gave error like missing config, then i tried this /restart=disabledefender , it restarted in safe mode then did its work then restarted again, the defender is disabled, but now on win11 i can't open optimizer. i will attach the log, i don't know where to get the dump file from.
[Optimizer.log](https://github.com/hellzerg/optimizer/files/9128414/Optimizer.log)

**Comment by hellzerg** [comment]
So, you tell me that after disabling defender the problem appeared?

**Comment by PhoenixCODE2322** [comment]
@hellzerg yes kind of .... like .. i decided to disable defender ..so i went to github read the info you posted on disabling the defender. Then i rebooted to safe mode and then i tried opening optimizer but it won't open so i thought maybe a bug in safe mode , so i used the argument using cmd  to disable the defender theb when i later booted into system , i checked and optimizer was not opening there too

**Comment by hellzerg** [comment]
But did it run before all this?

**Comment by PhoenixCODE2322** [comment]
@hellzerg yes , i used it thrice , but i do know excatly when and why it stopped working , i only noticied this when i booted into safe mode and tried to run it

**Comment by hellzerg** [comment]
Did you try deleting the Optimizer folder in ProgramData and then running the app in normal mode?

**Comment by Hunterok228** [comment]
I have the same problem, the program starts but then closes after a few seconds, what could be the reason? windows defender disabled

**Comment by anton8788** [comment]
Hi, so I have been using Optimizer 4.9 for 4 years now and never ran into any issues. However sold my old laptop, and bought myself a new one. Installed Optimizer 4.9 again and ran It without issue. Couple of weeks later, suddenly when I click to launch nothing happens.. It does not even want to start the process. I will upload the crash files here and also I tried installing the 16.9 version, same thing does not want to launch

**Comment by anton8788** [comment]
@hellzerg here are the crash dumps. I also tried to open the crash files myself in winDbg but all I get is question marks..

[CrashDumps.zip](https://github.com/user-attachments/files/18700190/CrashDumps.zip)
