### ISSUE TITLE
Disable automatic Updates error.

### ISSUE THREAD

**Issue by TheWishKid** [hellzerg/optimizer#275]
When i'm trying to uncheck "Disable automatic Update" an error occurs.
Because of this error i can't uncheck this option.

**Comment by hellzerg** [comment]
Can you send me the optimizer.log file located in C:\ProgramData\Optimizer?

@TheWishKid

**Comment by TheWishKid** [comment]
Sure, here it is

Windows 11 Home - (64-bit)
Optimizer 14.5 - .NET Framework 4.8 - Experimental build: False


[ERROR] [12/18/2022 10:03:31 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()


[ERROR] [12/18/2022 10:03:49 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()


[ERROR] [12/18/2022 10:05:02 PM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-


[ERROR] [12/18/2022 10:05:02 PM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.Optimize.DisableVisualStudioTelemetry()


[ERROR] [12/18/2022 10:05:48 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()


[ERROR] [12/18/2022 10:07:13 PM] in function [MainForm.CleanPC]
Could not find a part of the path 'C:\Users\fibix\AppData\Roaming\Mozilla\Firefox\Profiles'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateDirectories(String path)
   at Optimizer.CleanHelper.PreviewFireFoxClean(Boolean cache, Boolean cookies, Boolean searchHistory)
   at Optimizer.MainForm.PreviewCleanPC()


[ERROR] [12/18/2022 10:46:36 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()


[ERROR] [12/18/2022 10:47:11 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()


[ERROR] [12/19/2022 4:11:05 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()


[ERROR] [12/19/2022 4:11:25 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()


@hellzerg

**Comment by hellzerg** [comment]
Fixed in v14.7.
