### ISSUE TITLE
Optimizer won't open.

### ISSUE THREAD

**Issue by seansnydercc** [hellzerg/optimizer#325]
I tried launching Optimizer from my downloads folder regularly and with admin perms.  The splash screen pops up and loads some things but then closes and the program never opens.

I have no logs in C:\ProgramData\Optimizer

First time trying to use the software. Windows 10.

**Comment by hellzerg** [comment]
Can you see which Language code is used in optimizer.json file?

@seansnydercc

**Comment by seansnydercc** [comment]
```
{
  "Theme": "153, 102, 204",
  "AppsFolder": "C:\\Users\\seans\\Downloads\\OptimizerDownloads",
  "EnableTray": false,
  "AutoStart": false,
  "LanguageCode": 0,
  "EnablePerformanceTweaks": false,
  "DisableNetworkThrottling": false,
  "DisableWindowsDefender": false,
  "DisableSystemRestore": false,
  "DisablePrintService": false,
  "DisableMediaPlayerSharing": false,
  "DisableErrorReporting": false,
  "DisableHomeGroup": false,
  "DisableSuperfetch": false,
  "DisableTelemetryTasks": false,
  "DisableCompatibilityAssistant": false,
  "DisableFaxService": false,
  "DisableSmartScreen": false,
  "DisableCloudClipboard": false,
  "DisableStickyKeys": false,
  "DisableHibernation": false,
  "DisableSMB1": false,
  "DisableSMB2": false,
  "DisableNTFSTimeStamp": false,
  "DisableSearch": false,
  "DisableOffice2016Telemetry": false,
  "DisableVisualStudioTelemetry": false,
  "DisableFirefoxTemeletry": false,
  "DisableChromeTelemetry": false,
  "DisableNVIDIATelemetry": false,
  "DisableEdgeDiscoverBar": false,
  "DisableEdgeTelemetry": false,
  "DisableOneDrive": false,
  "EnableLegacyVolumeSlider": false,
  "DisableQuickAccessHistory": false,
  "DisableStartMenuAds": false,
  "UninstallOneDrive": false,
  "DisableMyPeople": false,
  "DisableAutomaticUpdates": false,
  "ExcludeDrivers": false,
  "DisableTelemetryServices": false,
  "DisablePrivacyOptions": false,
  "DisableCortana": false,
  "DisableSensorServices": false,
  "DisableWindowsInk": false,
  "DisableSpellingTyping": false,
  "DisableXboxLive": false,
  "DisableGameBar": false,
  "DisableInsiderService": false,
  "DisableStoreUpdates": false,
  "EnableLongPaths": false,
  "RemoveCastToDevice": false,
  "EnableGamingMode": false,
  "TaskbarToLeft": false,
  "DisableSnapAssist": false,
  "DisableWidgets": false,
  "DisableChat": false,
  "ClassicMenu": false,
  "DisableTPMCheck": false,
  "CompactMode": false,
  "DisableStickers": false,
  "DisableVBS": false,
  "DisableHPET": false,
  "EnableLoginVerbose": false
}
```

**Comment by hellzerg** [comment]
Can you see if there's any error related to optimizer in event viewer?

@seansnydercc

**Comment by BlueDrakoPT** [comment]
Same here. Windows 10. Latest build don't start.

**Comment by BlueDrakoPT** [comment]
Application: Optimizer-15.1.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException
   at System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   at System.Number.ParseUInt32(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   at System.ComponentModel.UInt32Converter.FromString(System.String, System.Globalization.NumberFormatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext, System.Globalization.CultureInfo, System.Object)

Exception Info: System.Management.Automation.PSInvalidCastException
   at System.Management.Automation.LanguagePrimitives.ConvertStringToInteger(System.Object, System.Type, Boolean, System.Management.Automation.PSObject, System.IFormatProvider, System.Management.Automation.Runspaces.TypeTable)
   at System.Management.Automation.LanguagePrimitives+ConversionData`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.Type, Boolean, System.Management.Automation.PSObject, System.IFormatProvider, System.Management.Automation.Runspaces.TypeTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(System.Object, System.Type, Boolean, System.IFormatProvider, System.Management.Automation.Runspaces.TypeTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo[[System.UInt32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object)
   at System.Management.Automation.Security.SystemPolicy.GetDebugLockdownPolicy(System.String)
   at System.Management.Automation.Security.SystemPolicy.GetSystemLockdownPolicy()
   at System.Management.Automation.Runspaces.InitialSessionState..cctor()

Exception Info: System.TypeInitializationException
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(System.Reflection.Assembly, System.String, System.Management.Automation.PSSnapInInfo, System.Management.Automation.PSModuleInfo, Boolean, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateCmdletEntry> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.Management.Automation.Runspaces.SessionStateAliasEntry>> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateProviderEntry> ByRef, System.String ByRef)
   at System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.LoadPSSnapIn(System.Management.Automation.PSSnapInInfo)
   at System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.LoadPSSnapIns(System.Collections.ObjectModel.Collection`1<System.Management.Automation.PSSnapInInfo>, System.Management.Automation.Runspaces.PSConsoleLoadException ByRef)
   at System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.CreateDefaultConfiguration()
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(System.Management.Automation.Host.PSHost)
   at System.Management.Automation.PowerShell+Worker.CreateRunspaceIfNeededAndDoWork(System.Management.Automation.Runspaces.Runspace, Boolean)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSInvocationSettings)
   at System.Management.Automation.PowerShell.CoreInvoke[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSInvocationSettings)
   at System.Management.Automation.PowerShell.Invoke(System.Collections.IEnumerable, System.Management.Automation.PSInvocationSettings)
   at Optimizer.UWPHelper.GetUWPApps(Boolean)
   at Optimizer.MainForm.GetModernApps(Boolean)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(System.EventArgs)
   at Optimizer.MoonCheck.OnCheckedChanged(System.EventArgs)
   at System.Windows.Forms.CheckBox.set_CheckState(System.Windows.Forms.CheckState)
   at System.Windows.Forms.CheckBox.set_Checked(Boolean)
   at Optimizer.MainForm..ctor(Optimizer.SplashForm, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean)
   at Optimizer.Program.StartMainForm()
   at Optimizer.Program.Main(System.String[])

**Comment by BlueDrakoPT** [comment]
Faulting application name: Optimizer-15.1.exe, version: 0.0.0.0, time stamp: 0x644577ba
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2788, time stamp: 0x62e593d6
Exception code: 0xe0434352
Fault offset: 0x000000000002cb69
Faulting process id: 0x2f0
Faulting application start time: 0x01d9767598663a00
Faulting application path: D:\Downloads\Optimizer-15.1.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 67626c5e-4086-4dec-ad27-cfb1e6cf86a1
Faulting package full name: 
Faulting package-relative application ID:

**Comment by hellzerg** [comment]
Okay. I got it. It will get fixed soon. Today you will try a testing release so we can be sure.

@seansnydercc I will ping you

**Comment by BlueDrakoPT** [comment]
Hi Helzerg! Microsoft changed something in latest NET update? everything was fine 2 days ago... :-)

**Comment by hellzerg** [comment]
@BlueDrakoPT I will research it and send you today or tomorrow a testing update.

**Comment by hellzerg** [comment]
@BlueDrakoPT 
It should work now in v15.2

**Comment by BlueDrakoPT** [comment]
Yes. It works. Thanks hellzerg!!!
