### ISSUE TITLE
Crash on win 8.1 tablet

### ISSUE THREAD

**Issue by SoNickRND** [hellzerg/optimizer#364]
Crash on Win 8.1 tablet
How can I obtain the log, if you need it?

**Comment by hellzerg** [comment]
@SoNickRND 

It's in C:\ProgramData\Optimizer\optimizer.log

**Comment by SoNickRND** [comment]
```
Windows 8.1 Single Language - (32-bit)
Optimizer 15.4 - .NET Framework 4.5.1 - Experimental build: False


[ERROR] [7/17/2023 3:11:19 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()


[ERROR] [7/17/2023 3:12:49 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()



```

**Comment by hellzerg** [comment]
@SoNickRND 

Unfortunately, this does not shed any light. It seems the crash is more deep.
You should look into event viewer.

**Comment by SoNickRND** [comment]
It seems, after installing more updates it start working.

**Comment by hellzerg** [comment]
what do you mean? You had an old version of the app?
@SoNickRND

**Comment by SoNickRND** [comment]
Nope, I got this tablet after resetting, and Windows downloaded and installed Win updates in a few batches. 
Between the "Optimizer not running" state and the "I want to reproduce the error and check event viewer" state, I let it restart and install downloaded updates last evening. And today the Optimizer did not crash.
So, recipe for fixing was "install all updates for Windows 8.1".

**Comment by hellzerg** [comment]
Ok, so .NET 4.8 was missing and got installed with latest updates.
@SoNickRND
