### ISSUE TITLE
optimizer 15.5 crashes when I open it

### ISSUE THREAD

**Issue by czz404** [hellzerg/optimizer#370]
**Describe the bug**
optimizer 15.5 crashes when I open it
I would be very grateful if you could tell me how to solve this problem  :)

**Logs**
Windows 11 Pro - 22H2 (64-bit)
Optimizer 15.5 - .NET Framework 4.8 - Experimental build: False

[ERROR] [7/22/2023 9:36:05 PM] in function [[Program.Main-UnhandledException]]
An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Optimizer.UWPHelper.GetUWPApps(Boolean showAll)
   at Optimizer.MainForm.GetModernApps(Boolean showAll)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at Optimizer.MoonCheck.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.set_Checked(Boolean value)
   at Optimizer.MainForm..ctor(SplashForm _splashForm, Boolean disableIndicium, Boolean disableHostsEditor, Boolean disableCommonApps, Boolean disableUWPApps, Boolean disableStartups, Boolean disableCleaner, Boolean disableIntegrator, Boolean disablePinger)
   at Optimizer.Program.StartMainForm()
   at Optimizer.Program.Main(String[] switches)

**Comment by hellzerg** [comment]
Just fixed with v15.6.
Sorry for the inconvinience.
