### ISSUE TITLE
log eror

### ISSUE THREAD

**Issue by SsS1z1Z1z1SsS** [hellzerg/optimizer#398]
Windows 11 Pro - 22H2 (64-bit)
Optimizer 15.8 - .NET Framework 4.8 - Experimental build: False

[ERROR] [10/11/2023 3:30:32 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [10/11/2023 3:31:18 AM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-

[ERROR] [10/11/2023 3:31:18 AM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.OptimizeHelper.DisableVisualStudioTelemetry()

[ERROR] [10/11/2023 3:36:03 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [10/11/2023 3:37:36 AM] in function [Utilities.RestartExplorer]
Отказано в доступе

   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Optimizer.Utilities.RestartExplorer()

[ERROR] [10/11/2023 3:37:36 AM] in function [Utilities.RestartExplorer]
Отказано в доступе

   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Optimizer.Utilities.RestartExplorer()

[ERROR] [10/11/2023 3:37:36 AM] in function [Utilities.RestartExplorer]
Отказано в доступе

   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Optimizer.Utilities.RestartExplorer()

[ERROR] [10/11/2023 3:37:36 AM] in function [Utilities.RestartExplorer]
Отказано в доступе

   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Optimizer.Utilities.RestartExplorer()

[ERROR] [10/11/2023 3:37:36 AM] in function [Utilities.RestartExplorer]
Отказано в доступе

   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Optimizer.Utilities.RestartExplorer()

[ERROR] [10/11/2023 3:37:36 AM] in function [Utilities.RestartExplorer]
Отказано в доступе

   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Optimizer.Utilities.RestartExplorer()

[ERROR] [10/11/2023 3:37:36 AM] in function [Utilities.RestartExplorer]
Отказано в доступе

   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Optimizer.Utilities.RestartExplorer()

[ERROR] [10/11/2023 3:37:36 AM] in function [Utilities.RestartExplorer]
Отказано в доступе

   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Optimizer.Utilities.RestartExplorer()

[ERROR] [10/11/2023 3:37:36 AM] in function [Utilities.RestartExplorer]
Unable to enumerate the process modules.

   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Optimizer.Utilities.RestartExplorer()

[ERROR] [10/11/2023 3:37:36 AM] in function [Utilities.RestartExplorer]
Unable to enumerate the process modules.

   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Optimizer.Utilities.RestartExplorer()

**Comment by hellzerg** [comment]
if you don't experience an issue with the app, these are pretty common non-issue errors.
