### ISSUE TITLE
View errors 

### ISSUE THREAD

**Issue by Aka7OJO** [hellzerg/optimizer#429]
I have his errors I do not really know what it. 

Windows 11 Home - 22H2 (64-bit)
Optimizer 16.2 - .NET Framework 4.8 - Experimental build: False

[ERROR] [11/22/2023 2:14:14 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [11/22/2023 2:20:35 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [11/22/2023 2:25:33 AM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-

[ERROR] [11/22/2023 2:25:33 AM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.OptimizeHelper.DisableVisualStudioTelemetry()

[ERROR] [11/22/2023 3:21:55 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [11/22/2023 12:48:49 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [11/22/2023 2:11:11 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [11/22/2023 4:43:05 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [11/22/2023 4:48:49 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

**Comment by hellzerg** [comment]
@Aka7OJO Common errors. Not something you need to be worried about
