### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by hagamingpc** [hellzerg/optimizer#490]
Windows 11 Home Single Language - 23H2 (64-bit)
Optimizer 15.8 - .NET Framework 4.8 - Experimental build: False

[ERROR] [10/10/2023 5:29:25 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [10/10/2023 5:30:05 PM] in function [MainForm.GetFeed-DownloadImages]
Unable to connect to the remote server

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at Optimizer.MainForm.GetFeed()

[ERROR] [10/10/2023 5:30:45 PM] in function [MainForm.CheckForUpdate]
Unable to connect to the remote server

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Optimizer.MainForm.CheckForUpdate(Boolean silentCheck)

[ERROR] [10/10/2023 5:37:47 PM] in function [Utilities.StartService]
Cannot start service DiagTrack on computer '.'.

   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Optimizer.Utilities.StartService(String serviceName)

[ERROR] [10/10/2023 5:41:01 PM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-

[ERROR] [10/10/2023 5:41:01 PM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.OptimizeHelper.DisableVisualStudioTelemetry()

[ERROR] [10/13/2023 8:58:57 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [10/13/2023 8:58:57 AM] in function [MainForm.GetFeed-DownloadImages]
The remote name could not be resolved: 'raw.githubusercontent.com'

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at Optimizer.MainForm.GetFeed()

[ERROR] [12/21/2023 6:02:12 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [12/21/2023 6:02:51 PM] in function [MainForm.GetFeed-DownloadImages]
Unable to connect to the remote server

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at Optimizer.MainForm.GetFeed()

[ERROR] [12/21/2023 6:03:31 PM] in function [MainForm.CheckForUpdate]
Unable to connect to the remote server

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Optimizer.MainForm.CheckForUpdate(Boolean silentCheck)

[ERROR] [12/21/2023 6:11:05 PM] in function [MainForm.CheckForUpdate]
Unable to connect to the remote server

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Optimizer.MainForm.CheckForUpdate(Boolean silentCheck)

[ERROR] [12/21/2023 6:12:29 PM] in function [MainForm.GetFeed-DownloadImages]
Unable to connect to the remote server

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at Optimizer.MainForm.GetFeed()

[ERROR] [12/21/2023 6:13:07 PM] in function [MainForm.GetFeed-DownloadImages]
Unable to connect to the remote server

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at Optimizer.MainForm.GetFeed()

[ERROR] [12/29/2023 11:04:28 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [12/29/2023 11:05:07 PM] in function [MainForm.GetFeed-DownloadImages]
Unable to connect to the remote server

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at Optimizer.MainForm.GetFeed()

[ERROR] [12/29/2023 11:05:48 PM] in function [MainForm.CheckForUpdate]
Unable to connect to the remote server

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Optimizer.MainForm.CheckForUpdate(Boolean silentCheck)

[ERROR] [12/29/2023 11:07:04 PM] in function [Utilities.StartService]
Cannot start service WSearch on computer '.'.

   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Optimizer.Utilities.StartService(String serviceName)

[ERROR] [1/16/2024 1:27:45 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [1/16/2024 1:27:45 PM] in function [MainForm.GetFeed-DownloadImages]
The remote name could not be resolved: 'raw.githubusercontent.com'

   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at Optimizer.MainForm.GetFeed()

[ERROR] [1/22/2024 3:13:36 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [1/22/2024 3:15:19 PM] in function [Utilities.StartService]
Cannot start service DiagTrack on computer '.'.

   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Optimizer.Utilities.StartService(String serviceName)

[ERROR] [1/22/2024 3:15:19 PM] in function [Utilities.StartService]
Cannot start service diagnosticshub.standardcollector.service on computer '.'.

   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Optimizer.Utilities.StartService(String serviceName)

[ERROR] [1/22/2024 3:15:19 PM] in function [Utilities.StartService]
Cannot start service dmwappushservice on computer '.'.

   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Optimizer.Utilities.StartService(String serviceName)

[ERROR] [3/26/2024 8:14:28 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [4/16/2024 7:33:26 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [4/16/2024 8:06:06 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [4/16/2024 9:10:43 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [4/16/2024 9:14:42 PM] in function [Utilities.StartService]
Cannot start service DiagTrack on computer '.'.

   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Optimizer.Utilities.StartService(String serviceName)

[ERROR] [4/16/2024 9:14:42 PM] in function [Optimize.DisablePerformanceTweaks]
Object reference not set to an instance of an object.

   at Optimizer.OptimizeHelper.DisablePerformanceTweaks()

[ERROR] [4/16/2024 9:35:00 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [4/16/2024 9:43:22 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

**Comment by hellzerg** [comment]
Typical errors. Nothing to worry about.
