### ISSUE TITLE
Many features not working

### ISSUE THREAD

**Issue by stucker9** [hellzerg/optimizer#512]
**Describe the bug**
A lot of features such as align taskbar to left, restore classic right click menu, and seemingly all of these similar features seem to be inoperable despite performing the restart as requested in the program.

**Expected behavior**
Taskbar aligned to left, classic right click menu restored

**Screenshots**
None needed

**Logs**
Windows 11 Pro - 21H2 (64-bit)
Optimizer 16.5 - .NET Framework 4.8 - Experimental build: False

[ERROR] [6/10/2024 8:15:13 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [6/10/2024 8:37:59 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [6/10/2024 8:51:26 AM] in function [Program.Main-UnhandledException]
Invoke or BeginInvoke cannot be called on a control until the window handle has been created.

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Post(SendOrPostCallback d, Object state)
   at System.Net.WebClient.InvokeOperationCompleted(AsyncOperation asyncOp, SendOrPostCallback callback, AsyncCompletedEventArgs eventArgs)
   at System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

[ERROR] [6/10/2024 9:05:11 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [6/10/2024 9:14:43 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

**Desktop (please complete the following information):**
 - Win11 Pro 21H2 BUILD 22000.2538
- .net frameworks: all
- Optimizer version: latest

**Comment by hellzerg** [comment]
@stucker9 

If your PC is joined in a ActiveDirectory domain, this is normal because I cannot override the policies coming from the joined domain.

If not, that is strange
