### ISSUE TITLE
I cant use UWP App feature

### ISSUE THREAD

**Issue by lequangcuong123** [hellzerg/optimizer#567]
**Describe the bug**

UWP App feature is unable to use
**Expected behavior**

When clicking Refresh will automatically list all applications
**Screenshots**
![Screenshot 2024-10-28 202516](https://github.com/user-attachments/assets/44159250-4c8b-428c-904e-263dd796a80e)

**Logs**
sorry, i cant see the log folder. Could you help me to find that?

**Desktop (please complete the following information):**
 - Window 11 pro 24h2
- installed .Net Framework 3.5, .Net Framework 4.8 advanced service
 - Optimizer 16.7 version

**Comment by lequangcuong123** [comment]
Windows 11 Pro - 24H2 (64-bit)
Optimizer 16.7 - .NET Framework 4.8 - Experimental build: False


[ERROR] [10/24/2024 1:52:22 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()


[ERROR] [10/24/2024 1:54:09 AM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-


[ERROR] [10/24/2024 1:54:09 AM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.OptimizeHelper.DisableVisualStudioTelemetry()


[ERROR] [10/24/2024 2:00:27 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()


[ERROR] [10/24/2024 11:29:10 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()


[ERROR] [10/24/2024 12:28:43 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()


[ERROR] [10/24/2024 12:29:04 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()


[ERROR] [10/24/2024 4:47:00 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()


[ERROR] [10/24/2024 7:43:28 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()


[ERROR] [10/24/2024 7:43:44 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()


[ERROR] [10/25/2024 10:02:08 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()


[ERROR] [10/28/2024 8:13:43 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()


[ERROR] [10/28/2024 8:18:09 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

**Comment by lequangcuong123** [comment]
here is the logs file:
[Optimizer.log](https://github.com/user-attachments/files/17543218/Optimizer.log)
