### ISSUE TITLE
Unhandled Exception on hosts's entry delete

### ISSUE THREAD

**Issue by Ultrafeel** [hellzerg/optimizer#62]
1. Add AdBlock entries
2. select 1st entry 
3. Delete
4.  Unhandled Exception on hosts's entry delete. It happens several times. Some times  it doesn't.
`************** Exception Text **************
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot invoke a non-delegate type
   at CallSite.Target(Closure , CallSite , Object , String )
   at Optimizer.HostsHelper.RemoveEntry(String entry)
   at Optimizer.MainForm.button42_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by hellzerg** [comment]
That's because once you add TOO MANY entries in HOSTS file, DNS Client services is triggering a cache process, locking the file.
You need to wait for the caching process to finish, before doing a change again.
